### ISSUE TITLE
something went wrong while fetching items. should temp league be updated?

### ISSUE THREAD

**Issue by rt2252357** [5k-mirrors/poe-dashboard#2]
something went wrong while fetching items. should temp league be updated?

How to solve this ?

**Comment by thisismydesign** [comment]
Nothing you can do on your side, we'll look into it.

**Comment by thisismydesign** [comment]
Forgot about this, sorry. Fixed and also open-sourced the project.

**Comment by Jinnai** [comment]
Getting the same error for div cards.

**Comment by thisismydesign** [comment]
@Jinnai Thanks, created an issue for this: https://github.com/5k-mirrors/poe-dashboard/issues/4

The project is now open source so anyone can look into it and possibly provide a fix.
